<?php

namespace App\Modele\Repository;

use App\Modele\DataObject\ConventionAlternance;

class ConventionAlternanceRepository extends AbstractRepository
{
    public function recuperer()
    {
        $tableau = null;
        $pdoStatement = ConnexionBaseDeDonnee::getPdo()->query("SELECT * FROM ConventionAlternanceFinale JOIN ConventionAlternanceFinal2 ON ConventionAlternanceFinale.id = ConventionAlternanceFinal2.id");
        foreach ($pdoStatement as $objetFormatTableau) {
            $tableau[] = $this->construireDepuisTableau($objetFormatTableau);
        }
        return $tableau;
    }

    public function recupererAvecFiltre(array $parameters) : ?array {
        $colonesql = "";
        $values = null;
        $i=0;
        $j=0;
        if($parameters != null){
            foreach($parameters as $clef => $valeur){
                if($i != 0){
                    $colonesql .= " AND ";
                }
                $i = $i + 1;
                // type spécial
                if($clef == "type"){
                    $colonesql .= $clef . " IN (";
                    $cpt = count($valeur);
                    foreach($valeur as $valIn){
                        $colonesql .= ":".$valIn . "Tag";
                        if($cpt-1 != $j){
                            $colonesql .= ",";
                        }
                        $expressionType = $valIn . "Tag";
                        $values[$expressionType] = $valIn;
                        $j+=1;
                    }
                    $colonesql .= ")";


                }else{
                    $colonesql .= $clef . " = ";
                    $colonesql .= ":".$clef . "Tag";

                    $expression = $clef . "Tag";
                    $values[$expression] = $valeur;
                }
            }

        }
        $tableau = null;
        $sql = "SELECT * FROM ConventionAlternanceFinale c JOIN ConventionAlternanceFinal2 c1 ON c.id = c1.id WHERE ". $colonesql;
        $pdoStatement = ConnexionBaseDeDonnee::getPdo()->prepare($sql);

        $pdoStatement->execute($values);
        foreach ($pdoStatement as $objetFormatTableau) {
            $tableau[] = $this->construireDepuisTableau($objetFormatTableau);
        }
        return $tableau;
    }

    public static function sauvegarder(ConventionAlternance $conventionAlternance) : void {

        $sql = "INSERT INTO ConventionAlternanceFinale VALUES (:archiveeTag,
:gereEnDehorsDeStudeaTag,
:statutsOPCOTag,
:idTag,
:etablissementTag,
:formationTag,
:anneeDebutTag,
:anneeFinTag,
:genreAlternantEtuTag,
:nomAlternantEtuTag,
:prenomAlternantEtuTag,
:DateDeSaisieParEntrepriseTag,
:validationPedagogiqueMissionTag,
:ficheEnErreurTag,
:codeErreurTag,
:contratEtConventionEnvoyeEntrepriseTag,
:contratEtOuConventionSigneTag,
:dateNaissanceTag,
:communeNaissanceTag,
:paysNaissanceTag,
:nationaliteTag,
:travailleurHandicapeTag,
:titulairePermisConduireTag,
:numeroSecuriteSocialeTag,
:pasDeNumeroSecuriteSocialeTag,
:sportifHautNiveauTag,
:telephone1Tag,
:telephone2Tag,
:email1Tag,
:email2Tag,
:adresseTag,
:complementTag,
:codePostalTag,
:villeTag,
:genreRepresentantLegalTag,
:nomRepresentantLegalTag,
:prenomRepresentantLegalTag,
:adresse2Tag,
:complement2Tag,
:codePostal2Tag,
:ville2Tag,
:codeINETag,
:situationAvantContratTag,
:paysDernierDiplomePrepareTag,
:departementDernierDiplomePrepareTag,
:etablissementDernierDiplomePrepareTag,
:UAIEtablissementDernierDiplomePrepareTag,
:typeDiplomeTag,
:anneeTag,
:intituleTag,
:obtentionTag,
:derniereAnneeOuClasseSuivieTag,
:dernierDiplomeObtenueTag,
:entrepriseTemporaireTag,
:nomContactTemporaireTag,
:prenomContactTemporaireTag,
:emailContactTemporaireTag,
:telephoneContactTemporaireTag,
:siretTag,
:typeEmployeurTag,
:raisonSocialeTag,
:codeNAFTag,
:caisseRetraiteComplementaireTag,
:effectifTotalTag,
:adresseContactTag,
:complementAdresseContactTag,
:codePostalContactTag,
:villeContactTag,
:adresseContact2Tag,
:complementAdresseContact2Tag,
:codePostalContact2Tag,
:villeContact2Tag,
:genreDuDirecteurTag,
:nomDirecteurTag,
:prenomDirecteurTag,
:fonctionDirecteurTag,
:emailDirecteurTag,
:siretAdministrationTag)";

        $pdoStatement = ConnexionBaseDeDonnee::getPdo()->prepare($sql);

        $values = array(
            "archiveeTag" => $conventionAlternance->getArchivee(),
            "gereEnDehorsDeStudeaTag" => $conventionAlternance->getGereEnDehorsDeStudea(),
            "statutsOPCOTag" => $conventionAlternance->getStatutsOPCO(),
            "idTag" => $conventionAlternance->getId(),
            "etablissementTag" => $conventionAlternance->getEtablissement(),
            "formationTag" => $conventionAlternance->getFormation(),
            "anneeDebutTag" => $conventionAlternance->getAnneeDebut(),
            "anneeFinTag" => $conventionAlternance->getAnneeFin(),
            "genreAlternantEtuTag" => $conventionAlternance->getGenreAlternantEtu(),
            "nomAlternantEtuTag" => $conventionAlternance->getNomAlternantEtu(),
            "prenomAlternantEtuTag" => $conventionAlternance->getPrenomAlternantEtu(),
            "DateDeSaisieParEntrepriseTag" => $conventionAlternance->getDateDeSaisieParEntreprise(),
            "validationPedagogiqueMissionTag" => $conventionAlternance->getValidationPedagogiqueMission(),
            "ficheEnErreurTag" => $conventionAlternance->getFicheEnErreur(),
            "codeErreurTag" => $conventionAlternance->getCodeErreur(),
            "contratEtConventionEnvoyeEntrepriseTag" => $conventionAlternance->getContratEtConventionEnvoyeEntreprise(),
            "contratEtOuConventionSigneTag" => $conventionAlternance->getContratEtOuConventionSigne(),
            "dateNaissanceTag" => $conventionAlternance->getDateNaissance(),
            "communeNaissanceTag" => $conventionAlternance->getCommuneNaissance(),
            "paysNaissanceTag" => $conventionAlternance->getPaysNaissance(),
            "nationaliteTag" => $conventionAlternance->getNationalite(),
            "travailleurHandicapeTag" => $conventionAlternance->getTravailleurHandicape(),
            "titulairePermisConduireTag" => $conventionAlternance->getTitulairePermisConduire(),
            "numeroSecuriteSocialeTag" => $conventionAlternance->getNumeroSecuriteSociale(),
            "pasDeNumeroSecuriteSocialeTag" => $conventionAlternance->getPasDeNumeroSecuriteSociale(),
            "sportifHautNiveauTag" => $conventionAlternance->getSportifHautNiveau(),
            "telephone1Tag" => $conventionAlternance->getTelephone1(),
            "telephone2Tag" => $conventionAlternance->getTelephone2(),
            "email1Tag" => $conventionAlternance->getEmail1(),
            "email2Tag" => $conventionAlternance->getEmail2(),
            "adresseTag" => $conventionAlternance->getAdresse(),
            "complementTag" => $conventionAlternance->getComplement(),
            "codePostalTag" => $conventionAlternance->getCodePostal(),
            "villeTag" => $conventionAlternance->getVille(),
            "genreRepresentantLegalTag" => $conventionAlternance->getGenreRepresentantLegal(),
            "nomRepresentantLegalTag" => $conventionAlternance->getNomRepresentantLegal(),
            "prenomRepresentantLegalTag" => $conventionAlternance->getPrenomRepresentantLegal(),
            "adresse2Tag" => $conventionAlternance->getAdresse2(),
            "complement2Tag" => $conventionAlternance->getComplement2(),
            "codePostal2Tag" => $conventionAlternance->getCodePostal2(),
            "ville2Tag" => $conventionAlternance->getVille2(),
            "codeINETag" => $conventionAlternance->getCodeINE(),
            "situationAvantContratTag" => $conventionAlternance->getSituationAvantContrat(),
            "paysDernierDiplomePrepareTag" => $conventionAlternance->getPaysDernierDiplomePrepare(),
            "departementDernierDiplomePrepareTag" => $conventionAlternance->getDepartementDernierDiplomePrepare(),
            "etablissementDernierDiplomePrepareTag" => $conventionAlternance->getEtablissementDernierDiplomePrepare(),
            "UAIEtablissementDernierDiplomePrepareTag" => $conventionAlternance->getUAIEtablissementDernierDiplomePrepare(),
            "typeDiplomeTag" => $conventionAlternance->getTypeDiplome(),
            "anneeTag" => $conventionAlternance->getAnnee(),
            "intituleTag" => $conventionAlternance->getIntitule(),
            "obtentionTag" => $conventionAlternance->getObtention(),
            "derniereAnneeOuClasseSuivieTag" => $conventionAlternance->getDerniereAnneeOuClasseSuivie(),
            "dernierDiplomeObtenueTag" => $conventionAlternance->getDernierDiplomeObtenue(),
            "entrepriseTemporaireTag" => $conventionAlternance->getEntrepriseTemporaire(),
            "nomContactTemporaireTag" => $conventionAlternance->getNomContactTemporaire(),
            "prenomContactTemporaireTag" => $conventionAlternance->getPrenomContactTemporaire(),
            "emailContactTemporaireTag" => $conventionAlternance->getEmailContactTemporaire(),
            "telephoneContactTemporaireTag" => $conventionAlternance->getTelephoneContactTemporaire(),
            "siretTag" => $conventionAlternance->getSiret(),
            "typeEmployeurTag" => $conventionAlternance->getTypeEmployeur(),
            "raisonSocialeTag" => $conventionAlternance->getRaisonSociale(),
            "codeNAFTag" => $conventionAlternance->getCodeNAF(),
            "caisseRetraiteComplementaireTag" => $conventionAlternance->getCaisseRetraiteComplementaire(),
            "effectifTotalTag" => $conventionAlternance->getEffectifTotal(),
            "adresseContactTag" => $conventionAlternance->getAdresseContact(),
            "complementAdresseContactTag" => $conventionAlternance->getComplementAdresseContact(),
            "codePostalContactTag" => $conventionAlternance->getCodePostalContact(),
            "villeContactTag" => $conventionAlternance->getVilleContact(),
            "adresseContact2Tag" => $conventionAlternance->getAdresseContact2(),
            "complementAdresseContact2Tag" => $conventionAlternance->getComplementAdresseContact2(),
            "codePostalContact2Tag" => $conventionAlternance->getCodePostalContact2(),
            "villeContact2Tag" => $conventionAlternance->getVilleContact2(),
            "genreDuDirecteurTag" => $conventionAlternance->getGenreDuDirecteur(),
            "nomDirecteurTag" => $conventionAlternance->getNomDirecteur(),
            "prenomDirecteurTag" => $conventionAlternance->getPrenomDirecteur(),
            "fonctionDirecteurTag" => $conventionAlternance->getFonctionDirecteur(),
            "emailDirecteurTag" => $conventionAlternance->getEmailDirecteur(),
            "siretAdministrationTag" => $conventionAlternance->getSiretAdministration()
        );
        $pdoStatement->execute($values);


        $sql2 = "INSERT INTO ConventionAlternanceFinal2 VALUES (:idTag,
:typeEmployeurDirecteurTag,
:raisonSocialDirecteurTag,
:codeNAFDirecteurTag,
:caisseRetraiteComplementaireDirecteurTag,
:effectifTotalDirecteurTag,
:adresseDirecteurTag,
:complementAdresseDirecteurTag,
:codePostalDirecteurTag,
:villeDirecteurTag,
:genreDirecteur2Tag,
:nomDirecteur2Tag,
:prenomDirecteur2Tag,
:fonctionDirecteur2Tag,
:emailDirecteur2Tag,
:genreInterlocuteurRHTag,
:nomInterlocuteurRHTag,
:prenomInterlocuteurRHTag,
:fonctionInterlocuteurRHTag,
:emailInterlocuteurRHTag,
:OPCOTag,
:IDCCTag,
:codeIDCCTag,
:missionSaisieTag,
:fichierJointMissionTag,
:mandatCFATag,
:typeContratTag,
:dateDebutContratTag,
:dateFinContratTag,
:genreMaitreApprentissageTag,
:nomMaitreApprentissageTag,
:prenomMaitreApprentissageTag,
:fonctionMaitreApprentissageTag,
:telephoneMaitreApprentissageTag,
:emailMaitreApprentissageTag,
:dateNaissanceMaitreApprentissageTag,
:dejaMaitreApprentissageTag,
:dejaFormationMaitreApprentissageTag,
:genreSecondMaitreApprentissageTag,
:nomSecondMaitreApprentissageTag,
:prenomSecondMaitreApprentissageTag,
:fonctionSecondMaitreApprentissageTag,
:telephoneSecondMaitreApprentissageTag,
:emailSecondMaitreApprentissageTag,
:dateNaissanceSecondMaitreApprentissageTag,
:dejaSecondMaitreApprentissageTag,
:dejaFormationSecondMaitreApprentissageTag,
:responsableDeFormationTag,
:validateurDevisTag,
:dureeContratTag,
:coutContratTag,
:montantPriseEnChargeNPECTag,
:montantResteChargeTag,
:coutFormationAnneeTag,
:coutContratAvantNegociationTag,
:numeroDECATag,
:codeDiplomeTag,
:codeRNCPTag,
:SFPTag,
:dateEnvoieSFPTag,
:gestionnaireEnvoieSFPTag,
:dureeSFPTag,
:dateDebutFormationTag,
:dateFinFormationTag,
:etablissementDocEmployeurTag,
:dateEtablissementDocEmployeurTag)";

        $pdoStatement2 = ConnexionBaseDeDonnee::getPdo()->prepare($sql2);

        $values2 = array(
            "idTag" => $conventionAlternance->getId(),
            "typeEmployeurDirecteurTag" => $conventionAlternance->getTypeEmployeurDirecteur(),
            "raisonSocialDirecteurTag" => $conventionAlternance->getRaisonSocialDirecteur(),
            "codeNAFDirecteurTag" => $conventionAlternance->getCodeNAFDirecteur(),
            "caisseRetraiteComplementaireDirecteurTag" => $conventionAlternance->getCaisseRetraiteComplementaireDirecteur(),
            "effectifTotalDirecteurTag" => $conventionAlternance->getEffectifTotalDirecteur(),
            "adresseDirecteurTag" => $conventionAlternance->getAdresseDirecteur(),
            "complementAdresseDirecteurTag" => $conventionAlternance->getComplementAdresseDirecteur(),
            "codePostalDirecteurTag" => $conventionAlternance->getCodePostalDirecteur(),
            "villeDirecteurTag" => $conventionAlternance->getVilleDirecteur(),
            "genreDirecteur2Tag" => $conventionAlternance->getGenreDirecteur2(),
            "nomDirecteur2Tag" => $conventionAlternance->getNomDirecteur2(),
            "prenomDirecteur2Tag" => $conventionAlternance->getPrenomDirecteur2(),
            "fonctionDirecteur2Tag" => $conventionAlternance->getFonctionDirecteur2(),
            "emailDirecteur2Tag" => $conventionAlternance->getEmailDirecteur2(),
            "genreInterlocuteurRHTag" => $conventionAlternance->getGenreInterlocuteurRH(),
            "nomInterlocuteurRHTag" => $conventionAlternance->getNomInterlocuteurRH(),
            "prenomInterlocuteurRHTag" => $conventionAlternance->getPrenomInterlocuteurRH(),
            "fonctionInterlocuteurRHTag" => $conventionAlternance->getFonctionInterlocuteurRH(),
            "emailInterlocuteurRHTag" => $conventionAlternance->getEmailInterlocuteurRH(),
            "OPCOTag" => $conventionAlternance->getOPCO(),
            "IDCCTag" => $conventionAlternance->getIDCC(),
            "codeIDCCTag" => $conventionAlternance->getCodeIDCC(),
            "missionSaisieTag" => $conventionAlternance->getMissionSaisie(),
            "fichierJointMissionTag" => $conventionAlternance->getFichierJointMission(),
            "mandatCFATag" => $conventionAlternance->getMandatCFA(),
            "typeContratTag" => $conventionAlternance->getTypeContrat(),
            "dateDebutContratTag" => $conventionAlternance->getDateDebutContrat(),
            "dateFinContratTag" => $conventionAlternance->getDateFinContrat(),
            "genreMaitreApprentissageTag" => $conventionAlternance->getGenreMaitreApprentissage(),
            "nomMaitreApprentissageTag" => $conventionAlternance->getNomMaitreApprentissage(),
            "prenomMaitreApprentissageTag" => $conventionAlternance->getPrenomMaitreApprentissage(),
            "fonctionMaitreApprentissageTag" => $conventionAlternance->getFonctionMaitreApprentissage(),
            "telephoneMaitreApprentissageTag" => $conventionAlternance->getTelephoneMaitreApprentissage(),
            "emailMaitreApprentissageTag" => $conventionAlternance->getEmailMaitreApprentissage(),
            "dateNaissanceMaitreApprentissageTag" => $conventionAlternance->getDateNaissanceMaitreApprentissage(),
            "dejaMaitreApprentissageTag" => $conventionAlternance->getDejaMaitreApprentissage(),
            "dejaFormationMaitreApprentissageTag" => $conventionAlternance->getDejaFormationMaitreApprentissage(),
            "genreSecondMaitreApprentissageTag" => $conventionAlternance->getGenreSecondMaitreApprentissage(),
            "nomSecondMaitreApprentissageTag" => $conventionAlternance->getNomSecondMaitreApprentissage(),
            "prenomSecondMaitreApprentissageTag" => $conventionAlternance->getPrenomSecondMaitreApprentissage(),
            "fonctionSecondMaitreApprentissageTag" => $conventionAlternance->getFonctionSecondMaitreApprentissage(),
            "telephoneSecondMaitreApprentissageTag" => $conventionAlternance->getTelephoneSecondMaitreApprentissage(),
            "emailSecondMaitreApprentissageTag" => $conventionAlternance->getEmailSecondMaitreApprentissage(),
            "dateNaissanceSecondMaitreApprentissageTag" => $conventionAlternance->getDateNaissanceSecondMaitreApprentissage(),
            "dejaSecondMaitreApprentissageTag" => $conventionAlternance->getDejaSecondMaitreApprentissage(),
            "dejaFormationSecondMaitreApprentissageTag" => $conventionAlternance->getDejaFormationSecondMaitreApprentissage(),
            "responsableDeFormationTag" => $conventionAlternance->getResponsableDeFormation(),
            "validateurDevisTag" => $conventionAlternance->getValidateurDevis(),
            "dureeContratTag" => $conventionAlternance->getDureeContrat(),
            "coutContratTag" => $conventionAlternance->getCoutContrat(),
            "montantPriseEnChargeNPECTag" => $conventionAlternance->getMontantPriseEnChargeNPEC(),
            "montantResteChargeTag" => $conventionAlternance->getMontantResteCharge(),
            "coutFormationAnneeTag" => $conventionAlternance->getCoutFormationAnnee(),
            "coutContratAvantNegociationTag" => $conventionAlternance->getCoutContratAvantNegociation(),
            "numeroDECATag" => $conventionAlternance->getNumeroDECA(),
            "codeDiplomeTag" => $conventionAlternance->getCodeDiplome(),
            "codeRNCPTag" => $conventionAlternance->getCodeRNCP(),
            "SFPTag" => $conventionAlternance->getSFP(),
            "dateEnvoieSFPTag" => $conventionAlternance->getDateEnvoieSFP(),
            "gestionnaireEnvoieSFPTag" => $conventionAlternance->getGestionnaireEnvoieSFP(),
            "dureeSFPTag" => $conventionAlternance->getDureeSFP(),
            "dateDebutFormationTag" => $conventionAlternance->getDateDebutFormation(),
            "dateFinFormationTag" => $conventionAlternance->getDateFinFormation(),
            "etablissementDocEmployeurTag" => $conventionAlternance->getEtablissementDocEmployeur(),
            "dateEtablissementDocEmployeurTag" => $conventionAlternance->getDateEtablissementDocEmployeur()

        );
        $pdoStatement2->execute($values2);

    }
    public function construireDepuisTableau(array $conventionFormatTableau): ConventionAlternance
    {
        $convention = new ConventionAlternance($conventionFormatTableau['archivee'],
            $conventionFormatTableau['gereEnDehorsDeStudea'],
            $conventionFormatTableau['statutsOPCO'],
            $conventionFormatTableau['id'],
            $conventionFormatTableau['etablissement'],
            $conventionFormatTableau['formation'],
            $conventionFormatTableau['anneeDebut'],
            $conventionFormatTableau['anneeFin'],
            $conventionFormatTableau['genreAlternantEtu'],
            $conventionFormatTableau['nomAlternantEtu'],
            $conventionFormatTableau['prenomAlternantEtu'],
            $conventionFormatTableau['DateDeSaisieParEntreprise'],
            $conventionFormatTableau['validationPedagogiqueMission'],
            $conventionFormatTableau['ficheEnErreur'],
            $conventionFormatTableau['codeErreur'],
            $conventionFormatTableau['contratEtConventionEnvoyeEntreprise'],
            $conventionFormatTableau['contratEtOuConventionSigne'],
            $conventionFormatTableau['dateNaissance'],
            $conventionFormatTableau['communeNaissance'],
            $conventionFormatTableau['paysNaissance'],
            $conventionFormatTableau['nationalite'],
            $conventionFormatTableau['travailleurHandicape'],
            $conventionFormatTableau['titulairePermisConduire'],
            $conventionFormatTableau['numeroSecuriteSociale'],
            $conventionFormatTableau['pasDeNumeroSecuriteSociale'],
            $conventionFormatTableau['sportifHautNiveau'],
            $conventionFormatTableau['telephone1'],
            $conventionFormatTableau['telephone2'],
            $conventionFormatTableau['email1'],
            $conventionFormatTableau['email2'],
            $conventionFormatTableau['adresse'],
            $conventionFormatTableau['complement'],
            $conventionFormatTableau['codePostal'],
            $conventionFormatTableau['ville'],
            $conventionFormatTableau['genreRepresentantLegal'],
            $conventionFormatTableau['nomRepresentantLegal'],
            $conventionFormatTableau['prenomRepresentantLegal'],
            $conventionFormatTableau['adresse2'],
            $conventionFormatTableau['complement2'],
            $conventionFormatTableau['codePostal2'],
            $conventionFormatTableau['ville2'],
            $conventionFormatTableau['codeINE'],
            $conventionFormatTableau['situationAvantContrat'],
            $conventionFormatTableau['paysDernierDiplomePrepare'],
            $conventionFormatTableau['departementDernierDiplomePrepare'],
            $conventionFormatTableau['etablissementDernierDiplomePrepare'],
            $conventionFormatTableau['UAIEtablissementDernierDiplomePrepare'],
            $conventionFormatTableau['typeDiplome'],
            $conventionFormatTableau['annee'],
            $conventionFormatTableau['intitule'],
            $conventionFormatTableau['obtention'],
            $conventionFormatTableau['derniereAnneeOuClasseSuivie'],
            $conventionFormatTableau['dernierDiplomeObtenue'],
            $conventionFormatTableau['entrepriseTemporaire'],
            $conventionFormatTableau['nomContactTemporaire'],
            $conventionFormatTableau['prenomContactTemporaire'],
            $conventionFormatTableau['emailContactTemporaire'],
            $conventionFormatTableau['telephoneContactTemporaire'],
            $conventionFormatTableau['siret'],
            $conventionFormatTableau['typeEmployeur'],
            $conventionFormatTableau['raisonSociale'],
            $conventionFormatTableau['codeNAF'],
            $conventionFormatTableau['caisseRetraiteComplementaire'],
            $conventionFormatTableau['effectifTotal'],
            $conventionFormatTableau['adresseContact'],
            $conventionFormatTableau['complementAdresseContact'],
            $conventionFormatTableau['codePostalContact'],
            $conventionFormatTableau['villeContact'],
            $conventionFormatTableau['adresseContact2'],
            $conventionFormatTableau['complementAdresseContact2'],
            $conventionFormatTableau['codePostalContact2'],
            $conventionFormatTableau['villeContact2'],
            $conventionFormatTableau['genreDuDirecteur'],
            $conventionFormatTableau['nomDirecteur'],
            $conventionFormatTableau['prenomDirecteur'],
            $conventionFormatTableau['fonctionDirecteur'],
            $conventionFormatTableau['emailDirecteur'],
            $conventionFormatTableau['siretAdministration'],
            $conventionFormatTableau['typeEmployeurDirecteur'],
            $conventionFormatTableau['raisonSocialDirecteur'],
            $conventionFormatTableau['codeNAFDirecteur'],
            $conventionFormatTableau['caisseRetraiteComplementaireDirecteur'],
            $conventionFormatTableau['effectifTotalDirecteur'],
            $conventionFormatTableau['adresseDirecteur'],
            $conventionFormatTableau['complementAdresseDirecteur'],
            $conventionFormatTableau['codePostalDirecteur'],
            $conventionFormatTableau['villeDirecteur'],
            $conventionFormatTableau['genreDirecteur2'],
            $conventionFormatTableau['nomDirecteur2'],
            $conventionFormatTableau['prenomDirecteur2'],
            $conventionFormatTableau['fonctionDirecteur2'],
            $conventionFormatTableau['emailDirecteur2'],
            $conventionFormatTableau['genreInterlocuteurRH'],
            $conventionFormatTableau['nomInterlocuteurRH'],
            $conventionFormatTableau['prenomInterlocuteurRH'],
            $conventionFormatTableau['fonctionInterlocuteurRH'],
            $conventionFormatTableau['emailInterlocuteurRH'],
            $conventionFormatTableau['OPCO'],
            $conventionFormatTableau['IDCC'],
            $conventionFormatTableau['codeIDCC'],
            $conventionFormatTableau['missionSaisie'],
            $conventionFormatTableau['fichierJointMission'],
            $conventionFormatTableau['mandatCFA'],
            $conventionFormatTableau['typeContrat'],
            $conventionFormatTableau['dateDebutContrat'],
            $conventionFormatTableau['dateFinContrat'],
            $conventionFormatTableau['genreMaitreApprentissage'],
            $conventionFormatTableau['nomMaitreApprentissage'],
            $conventionFormatTableau['prenomMaitreApprentissage'],
            $conventionFormatTableau['fonctionMaitreApprentissage'],
            $conventionFormatTableau['telephoneMaitreApprentissage'],
            $conventionFormatTableau['emailMaitreApprentissage'],
            $conventionFormatTableau['dateNaissanceMaitreApprentissage'],
            $conventionFormatTableau['dejaMaitreApprentissage'],
            $conventionFormatTableau['dejaFormationMaitreApprentissage'],
            $conventionFormatTableau['genreSecondMaitreApprentissage'],
            $conventionFormatTableau['nomSecondMaitreApprentissage'],
            $conventionFormatTableau['prenomSecondMaitreApprentissage'],
            $conventionFormatTableau['fonctionSecondMaitreApprentissage'],
            $conventionFormatTableau['telephoneSecondMaitreApprentissage'],
            $conventionFormatTableau['emailSecondMaitreApprentissage'],
            $conventionFormatTableau['dateNaissanceSecondMaitreApprentissage'],
            $conventionFormatTableau['dejaSecondMaitreApprentissage'],
            $conventionFormatTableau['dejaFormationSecondMaitreApprentissage'],
            $conventionFormatTableau['responsableDeFormation'],
            $conventionFormatTableau['validateurDevis'],
            $conventionFormatTableau['dureeContrat'],
            $conventionFormatTableau['coutContrat'],
            $conventionFormatTableau['montantPriseEnChargeNPEC'],
            $conventionFormatTableau['montantResteCharge'],
            $conventionFormatTableau['coutFormationAnnee'],
            $conventionFormatTableau['coutContratAvantNegociation'],
            $conventionFormatTableau['numeroDECA'],
            $conventionFormatTableau['codeDiplome'],
            $conventionFormatTableau['codeRNCP'],
            $conventionFormatTableau['SFP'],
            $conventionFormatTableau['dateEnvoieSFP'],
            $conventionFormatTableau['gestionnaireEnvoieSFP'],
            $conventionFormatTableau['dureeSFP'],
            $conventionFormatTableau['dateDebutFormation'],
            $conventionFormatTableau['dateFinFormation'],
            $conventionFormatTableau['etablissementDocEmployeur'],
            $conventionFormatTableau['dateEtablissementDocEmployeur']
        );

        return $convention;
    }
    public function getNomsColones(): array
    {
        return [
            "archivee",
            "gereEnDehorsDeStudea",
            "statutsOPCO",
            "id",
            "etablissement",
            "formation",
            "anneeDebut",
            "anneeFin",
            "genreAlternantEtu",
            "nomAlternantEtu",
            "prenomAlternantEtu",
            "DateDeSaisieParEntreprise",
            "validationPedagogiqueMission",
            "ficheEnErreur",
            "codeErreur",
            "contratEtConventionEnvoyeEntreprise",
            "contratEtOuConventionSigne",
            "dateNaissance",
            "communeNaissance",
            "paysNaissance",
            "nationalite",
            "travailleurHandicape",
            "titulairePermisConduire",
            "numeroSecuriteSociale",
            "pasDeNumeroSecuriteSociale",
            "sportifHautNiveau",
            "telephone1",
            "telephone2",
            "email1",
            "email2",
            "adresse",
            "complement",
            "codePostal",
            "ville",
            "genreRepresentantLegal",
            "nomRepresentantLegal",
            "prenomRepresentantLegal",
            "adresse2",
            "complement2",
            "codePostal2",
            "ville2",
            "codeINE",
            "situationAvantContrat",
            "paysDernierDiplomePrepare",
            "departementDernierDiplomePrepare",
            "etablissementDernierDiplomePrepare",
            "UAIEtablissementDernierDiplomePrepare",
            "typeDiplome",
            "annee",
            "intitule",
            "obtention",
            "derniereAnneeOuClasseSuivie",
            "dernierDiplomeObtenue",
            "entrepriseTemporaire",
            "nomContactTemporaire",
            "prenomContactTemporaire",
            "emailContactTemporaire",
            "telephoneContactTemporaire",
            "siret",
            "typeEmployeur",
            "raisonSociale",
            "codeNAF",
            "caisseRetraiteComplementaire",
            "effectifTotal",
            "adresseContact",
            "complementAdresseContact",
            "codePostalContact",
            "villeContact",
            "adresseContact2",
            "complementAdresseContact2",
            "codePostalContact2",
            "villeContact2",
            "genreDuDirecteur",
            "nomDirecteur",
            "prenomDirecteur",
            "fonctionDirecteur",
            "emailDirecteur",
            "siretAdministration",
            "typeEmployeurDirecteur",
            "raisonSocialDirecteur",
            "codeNAFDirecteur",
            "caisseRetraiteComplementaireDirecteur",
            "effectifTotalDirecteur",
            "adresseDirecteur",
            "complementAdresseDirecteur",
            "codePostalDirecteur",
            "villeDirecteur",
            "genreDirecteur2",
            "nomDirecteur2",
            "prenomDirecteur2",
            "fonctionDirecteur2",
            "emailDirecteur2",
            "genreInterlocuteurRH",
            "nomInterlocuteurRH",
            "prenomInterlocuteurRH",
            "fonctionInterlocuteurRH",
            "emailInterlocuteurRH",
            "OPCO",
            "IDCC",
            "codeIDCC",
            "missionSaisie",
            "fichierJointMission",
            "mandatCFA",
            "typeContrat",
            "dateDebutContrat",
            "dateFinContrat",
            "genreMaitreApprentissage",
            "nomMaitreApprentissage",
            "prenomMaitreApprentissage",
            "fonctionMaitreApprentissage",
            "telephoneMaitreApprentissage",
            "emailMaitreApprentissage",
            "dateNaissanceMaitreApprentissage",
            "dejaMaitreApprentissage",
            "dejaFormationMaitreApprentissage",
            "genreSecondMaitreApprentissage",
            "nomSecondMaitreApprentissage",
            "prenomSecondMaitreApprentissage",
            "fonctionSecondMaitreApprentissage",
            "telephoneSecondMaitreApprentissage",
            "emailSecondMaitreApprentissage",
            "dateNaissanceSecondMaitreApprentissage",
            "dejaSecondMaitreApprentissage",
            "dejaFormationSecondMaitreApprentissage",
            "responsableDeFormation",
            "validateurDevis",
            "dureeContrat",
            "coutContrat",
            "montantPriseEnChargeNPEC",
            "montantResteCharge",
            "coutFormationAnnee",
            "coutContratAvantNegociation",
            "numeroDECA",
            "codeDiplome",
            "codeRNCP",
            "SFP",
            "dateEnvoieSFP",
            "gestionnaireEnvoieSFP",
            "dureeSFP",
            "dateDebutFormation",
            "dateFinFormation",
            "etablissementDocEmployeur",
            "dateEtablissementDocEmployeur"
        ];
    }

    public function getNomClePrimaire(): string
    {
        return "id";
    }

    protected function getNomTable(): string
    {
        return "ConventionAlternanceFinale";
    }
}